import assert from 'node:assert/strict';
import {SECTORS,binary,freshState,validateSave,subnet,challenge,checkAnswer,award,canUnlock,restored,learningSupport,OSI_CASES,UPGRADES,SITE_COMPONENTS,WORKSTATION_REWARDS,availableModules,terminalAvailable,claimTerminal,openSector,canStartUplink,startUplink,STARTS,chooseRegion,regionFor,regionControl,worldControl,signalReward,registerMistake,scrambleTrace} from './dist/engine.js';
import {newTerminal,terminalCommand} from './dist/terminal.js';
let checks=0;const ok=(x,m)=>{assert.ok(x,m);checks++;};
for(let p=24;p<=30;p++)for(let n=0;n<256;n++){const s=subnet(n,p);ok(s.network===(n&s.mask),'network equals IP AND mask');ok(s.broadcast===(s.network|(255^s.mask)),'broadcast fills host bits');ok(n>=s.network&&n<=s.broadcast,'packet is contained');ok(s.hosts===s.broadcast-s.network-1,'usable hosts exclude endpoints');}
for(let sector=0;sector<6;sector++)for(let progress=0;progress<80;progress++)for(const seed of [0,.17,.53,.999999]){const q=challenge(sector,progress,()=>seed);ok(checkAnswer(q,q.expected),'generated answer accepted');ok(!checkAnswer(q,''),'blank rejected');ok(!checkAnswer(q,'nonsense'),'malformed answer rejected');if(q.kind==='bits')ok(q.expected>=0&&q.expected<2**q.width,'bit answer fits');if(q.kind==='choice')ok(q.options.includes(q.expected),'choice includes answer');}
ok(binary(0)==='00000000'&&binary(255)==='11111111','binary boundaries');
const state=freshState();for(let sector=0;sector<6;sector++){if(sector){ok(canUnlock(state,sector),'campaign can afford next sector');ok(openSector(state,sector),'site equipment installed');}for(let p=0;p<8;p++){const q=challenge(sector,p);state.attempts[sector]++;award(state,q);}ok(claimTerminal(state,sector),'workstation reward available');}
ok(Array.from({length:24},(_,i)=>restored(state,i)).every(Boolean),'all 24 relays restored');ok(state.total===48,'campaign practice counted');ok(state.shards===24,'campaign economy has surplus');ok(!canUnlock(state,5),'duplicate unlock prevented');
const st=freshState();st.upgrades=['yield','combo'];st.streak=2;ok(award(st,challenge(0,0))===21,'yield and streak bonus');st.overdrive=1;st.overCooldown=10;ok(award(st,challenge(0,0),{first:false,assisted:true})===12,'overdrive doubles energy');ok(st.streak===0&&st.assisted===1&&st.firstTry[0]===1,'assistance tracked');
ok(validateSave(JSON.parse(JSON.stringify(state))).total===48,'save roundtrip');assert.throws(()=>validateSave({...state,energy:-1}));assert.throws(()=>validateSave({...state,counts:[1]}));assert.throws(()=>validateSave({version:9}));checks+=3;

const support=freshState();ok(learningSupport(support,challenge(0,0)),'first four repairs have labels');support.counts[0]=4;ok(!learningSupport(support,challenge(0,4)),'four-bit labels fade');ok(learningSupport(support,challenge(0,4),true),'temporary help reveals labels');support.counts[1]=4;ok(!learningSupport(support,challenge(1,4)),'byte labels fade');ok(!learningSupport(support,challenge(2,0)),'IP work is independent');
for(let i=0;i<OSI_CASES.length;i++){const q=challenge(5,i);ok(q.expected.startsWith(String(OSI_CASES[i][1])+' · '),'OSI layer matches scenario');}
const old={...freshState(),version:1,sector:3,counts:[8,8,9,4,2,0],attempts:[8,8,9,4,2,0],firstTry:[8,8,9,4,2,0],unlocked:[0,1,2,3,4],energy:70,shards:1,upgrades:['drone','loop','speed','scanner','yield'],relayLevels:[1,2,3]};
const migrated=validateSave(old);ok(migrated.version===4,'save migrated');ok(migrated.counts.join(',')==='8,8,4,2,0,0','old skills remapped, OSI starts fresh');ok(migrated.sector===2,'active IP sector follows remap');ok(migrated.shards===19,'retired upgrades refunded');ok(migrated.energy===670,'amplifier investment refunded');ok(!migrated.won,'new OSI work still required');ok(migrated.upgrades.join(',')==='yield','valid upgrade retained');
const solutions=[['dir','cd tickets','type job.txt','ipconfig','ping 192.168.1.1'],['ipconfig','repair cable','ping 192.168.1.1'],['ipconfig','ipconfig /renew','ping 192.168.1.20'],['route print','configure gateway 192.168.1.1','ping 198.51.100.20'],['nslookup portal.test','configure dns 192.168.1.53','nslookup portal.test'],['curl http://portal.test','repair service','curl http://portal.test']];
for(let i=0;i<6;i++){const lab=newTerminal(i);ok(!terminalCommand(lab,'submit').completed,'case cannot be skipped');for(const cmd of solutions[i])terminalCommand(lab,cmd);ok(terminalCommand(lab,'submit').completed,'case '+i+' completable');}
let lab=newTerminal(3);ok(terminalCommand(lab,'ping 192.168.1.20').output.includes('Reply from'),'wrong gateway does not block local subnet');ok(terminalCommand(lab,'ping 198.51.100.20').output.includes('timed out'),'wrong gateway blocks remote route');
lab=newTerminal(4);ok(terminalCommand(lab,'ping 192.168.1.20').output.includes('Reply from'),'DNS failure does not block IP');ok(terminalCommand(lab,'ping portal.test').output.includes('could not find'),'DNS failure blocks name lookup');const previous=lab.dns;terminalCommand(lab,'configure dns 999.1.1.1');ok(lab.dns===previous,'invalid config does not mutate lab');ok(terminalCommand(lab,'fetch(https://example.com)').output.includes('not recognized'),'only allowlisted simulated commands accepted');
// Required hardware cannot be farmed through signals or repeat terminal submissions.
const blocked=freshState();for(let n=0;n<100;n++)award(blocked,challenge(0,n));
ok(!canUnlock(blocked,1),'binary grinding cannot bypass workstation');ok(!claimTerminal(blocked,1),'later case cannot be farmed early');
ok(claimTerminal(blocked,0),'first cache claimed');const before=JSON.stringify(blocked);ok(!claimTerminal(blocked,0),'repeat cache rejected');ok(JSON.stringify(blocked)===before,'duplicate reward has no side effects');
ok(openSector(blocked,1),'first module installs');ok(availableModules(blocked)===0,'module consumed');ok(!openSector(blocked,1),'cannot double install');ok(terminalAvailable(blocked,1),'next workstation unlocked');
ok(canStartUplink(state),'baseline campaign funds final uplink without grinding');const funds=state.energy;ok(startUplink(state),'final hardware installs');ok(state.energy===funds-300&&availableModules(state)===0,'final equipment charged');ok(startUplink(state)&&state.energy===funds-300,'resuming final never charges twice');
const legacy=validateSave({...state,version:2,won:false,upgrades:['routeLab','dnsLab','serviceLab'],energy:0,shards:0});ok(legacy.energy===180&&legacy.shards===8,'purchased casebooks refunded');ok(legacy.unlocked.length===6&&legacy.terminalCompleted.length===6,'old progress preserved');ok(availableModules(legacy)===6,'old completed cases receive modules');const again=validateSave(legacy);ok(again.energy===180&&again.shards===8,'migration refund occurs once');
const missingCase={...state,installedModules:[],terminalCompleted:[0,1,2,3,4],energy:1e6};ok(!canStartUplink(missingCase),'sixth workstation required even with abundant funds');
const bankrupt={...state,installedModules:[1,2,3,4,5],energy:0};ok(!startUplink(bankrupt),'insufficient final components cannot go negative');for(let n=0;n<22;n++)award(bankrupt,challenge(5,n),{first:false,assisted:true});ok(startUplink(bankrupt),'assisted practice recovers depleted budget');
// Buy every affordable optional upgrade along the route; renewable practice always recovers.
const shopper=freshState();let extra=0;for(let i=0;i<6;i++){for(let p=0;p<8;p++)award(shopper,challenge(i,p),{first:false,assisted:true});ok(claimTerminal(shopper,i),'required case never has a purchase gate');for(const u of UPGRADES){if(!shopper.upgrades.includes(u.id)&&u.needs.every(id=>shopper.upgrades.includes(id))&&(!u.sector||shopper.unlocked.includes(u.sector))&&shopper.energy>=u.credits&&shopper.shards>=u.cost){shopper.energy-=u.credits;shopper.shards-=u.cost;shopper.upgrades.push(u.id);}}if(i<5){let n=0;while(!canUnlock(shopper,i+1)&&n++<100){award(shopper,challenge(i,8+n),{first:false,assisted:true});extra++;}ok(openSector(shopper,i+1),'upgrade spending cannot soft-lock campaign');}}
while(!canStartUplink(shopper)&&extra<500){award(shopper,challenge(5,extra),{first:false,assisted:true});extra++;}ok(startUplink(shopper),'all-upgrade route can finish');
console.log('Economy: baseline components after final install = '+state.energy+'; extra practice with aggressive upgrades = '+extra);
console.log('PASS: '+checks+' assertions: campaign economy, generated answers, fading assistance, v1 migration/refunds, OSI scenarios, all six terminal cases and fault behavior.');

for(const start of STARTS){const s=freshState();ok(chooseRegion(s,start.id),'origin selectable');ok(!chooseRegion(s,'pacific'),'origin cannot be changed to stack perks');ok(new Set([0,1,2,3,4,5].map(i=>regionFor(s,i).name)).size===6,'route covers six unique regions');for(let i=0;i<6;i++){for(let p=0;p<8;p++)award(s,challenge(i,p),{first:false,assisted:true});claimTerminal(s,i);if(i<5)ok(openSector(s,i+1),'all starts can fund progression');}ok(worldControl(s)===100,'complete world control');ok(startUplink(s),'all starts can fund finale');}
const raid=freshState();chooseRegion(raid,'sahara');raid.energy=200;raid.shards=20;raid.counts[0]=8;claimTerminal(raid,0);const owned=raid.energy;ok(regionControl(raid,0)===5,'region starts liberated');for(let i=0;i<4;i++)registerMistake(raid,0);ok(raid.jammed[0]===2&&raid.raids===1,'four trace points trigger one raid');ok(regionControl(raid,0)===4,'raid temporarily contests objective');ok(raid.energy===owned&&raid.counts[0]===8,'raid preserves bank and learning');ok(!canUnlock(raid,1),'jam blocks expansion');for(let i=0;i<20;i++)registerMistake(raid,0);ok(raid.jammed[0]===2&&raid.raids===1,'raids do not stack during recovery');ok(signalReward(raid,challenge(0,0))===2,'jam halves salvage');award(raid,challenge(0,0),{first:false,assisted:true});ok(raid.jammed[0]===1,'first correct assisted repair weakens jam');award(raid,challenge(0,0));ok(raid.jammed[0]===0&&canUnlock(raid,1),'second repair restores expansion');ok(regionControl(raid,0)===5,'region recovered');
const stealth=freshState();chooseRegion(stealth,'cascadia');for(let i=0;i<5;i++)registerMistake(stealth,0);ok(!stealth.jammed[0],'Cascadia tolerates five trace points');registerMistake(stealth,0);ok(stealth.jammed[0]===2,'Cascadia raids at six');
const ghost=freshState();chooseRegion(ghost,'pacific');for(let i=0;i<3;i++)registerMistake(ghost,0);award(ghost,challenge(0,0));ok(ghost.heat[0]===1,'Pacific cools by two');registerMistake(ghost,0);ok(scrambleTrace(ghost,0)&&ghost.heat[0]===0,'ability clears trace');registerMistake(ghost,0);ok(!scrambleTrace(ghost,0),'ability cooldown enforced');for(let i=0;i<4;i++)award(ghost,challenge(0,i));registerMistake(ghost,0);ok(scrambleTrace(ghost,0),'ability recharges through play');
const savedRaid=validateSave(JSON.parse(JSON.stringify(stealth)));ok(savedRaid.region==='cascadia'&&savedRaid.jammed[0]===2,'raid and origin persist across reload');
const old3=validateSave({...state,version:3,region:undefined,heat:undefined,jammed:undefined});ok(old3.installedModules.length===state.installedModules.length,'prior installed hardware retained');ok(old3.region===null&&old3.counts[0]===state.counts[0],'old learning retained for origin choice');
console.log('WORLD CAMPAIGN PASS: '+checks+' total assertions, all origins, raids, abilities, migration, economy.');
